// Mirrors the same scenarios already used to test the skill set against
// Sample Data/*.csv in this repo (Hennessy/Patron/Grey Goose margins,
// Corona/Modelo/Baileys expiry, Casamigos demand pattern) — loading this in
// Settings lets you explore the ported logic against familiar numbers.
import type { Inquiry, Product, Sale } from "../types";
import { daysAgoIso } from "./businessLogic";

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "P001",
    name: "Hennessy VS",
    category: "Cognac",
    size: "50ml",
    qty: 86,
    reorderPoint: 40,
    purchasePrice: 4.1,
    sellingPrice: 7.99,
    expiryDate: "",
    vendor: "Southern Glazer's Wine & Spirits",
    receivedDate: daysAgoIso(22),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/2023_Hennessy_V.S._Cognac.jpg/500px-2023_Hennessy_V.S._Cognac.jpg",
  },
  {
    id: "P004",
    name: "Hennessy VS",
    category: "Cognac",
    size: "750ml",
    qty: 9,
    reorderPoint: 10,
    purchasePrice: 38.5,
    sellingPrice: 64.99,
    expiryDate: "",
    vendor: "Southern Glazer's Wine & Spirits",
    receivedDate: daysAgoIso(22),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/2023_Hennessy_V.S._Cognac.jpg/500px-2023_Hennessy_V.S._Cognac.jpg",
  },
  {
    id: "P008",
    name: "Patron Silver",
    category: "Tequila",
    size: "50ml",
    qty: 64,
    reorderPoint: 35,
    purchasePrice: 4.9,
    sellingPrice: 9.49,
    expiryDate: "",
    vendor: "Southern Glazer's Wine & Spirits",
    receivedDate: daysAgoIso(15),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Tequila_Silver%2C_Reposado%2C_and_Anejo.jpg/500px-Tequila_Silver%2C_Reposado%2C_and_Anejo.jpg",
  },
  {
    id: "P010",
    name: "Patron Silver",
    category: "Tequila",
    size: "750ml",
    qty: 11,
    reorderPoint: 12,
    purchasePrice: 39.0,
    sellingPrice: 64.99,
    expiryDate: "",
    vendor: "Southern Glazer's Wine & Spirits",
    receivedDate: daysAgoIso(15),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Tequila_Silver%2C_Reposado%2C_and_Anejo.jpg/500px-Tequila_Silver%2C_Reposado%2C_and_Anejo.jpg",
  },
  {
    id: "P015",
    name: "Grey Goose",
    category: "Vodka",
    size: "750ml",
    qty: 8,
    reorderPoint: 10,
    purchasePrice: 26.0,
    sellingPrice: 44.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(31),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Grey_Goose_Original_Vodka_02.tif/lossy-page1-500px-Grey_Goose_Original_Vodka_02.tif.jpg",
  },
  {
    id: "P016",
    name: "Baileys Irish Cream",
    category: "Cream Liqueur",
    size: "750ml",
    qty: 10,
    reorderPoint: 8,
    purchasePrice: 14.0,
    sellingPrice: 24.99,
    expiryDate: "2026-11-15",
    vendor: "Southern Glazer's Wine & Spirits",
    receivedDate: daysAgoIso(22),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Baileys_Irish_Cream_Liqueur_01.jpg/500px-Baileys_Irish_Cream_Liqueur_01.jpg",
  },
  {
    id: "P017",
    name: "Corona Extra 6-pack",
    category: "Beer",
    size: "6-pack",
    qty: 40,
    reorderPoint: 20,
    purchasePrice: 7.5,
    sellingPrice: 12.99,
    expiryDate: "2026-09-01",
    vendor: "Coastal Beverage Supply",
    receivedDate: daysAgoIso(9),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Corona_Extra_beer_bottle_%282019%29.png/500px-Corona_Extra_beer_bottle_%282019%29.png",
  },
  {
    id: "P018",
    name: "Modelo Especial 6-pack",
    category: "Beer",
    size: "6-pack",
    qty: 36,
    reorderPoint: 20,
    purchasePrice: 7.8,
    sellingPrice: 12.99,
    expiryDate: "2026-09-10",
    vendor: "Coastal Beverage Supply",
    receivedDate: daysAgoIso(9),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Cerveza_modelo_especial.jpg/500px-Cerveza_modelo_especial.jpg",
  },

  // Below: expanded catalog for testing the inventory card grid / detail
  // panel across more categories, vendors, stock levels, and shelf ages.
  // P001–P018 above stay untouched — businessLogic.test.ts asserts exact
  // values against several of those IDs.
  {
    id: "P019",
    name: "Jack Daniel's Old No. 7",
    category: "Whiskey",
    size: "750ml",
    qty: 28,
    reorderPoint: 20,
    purchasePrice: 22.0,
    sellingPrice: 34.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(8),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/US_Navy_090518-N-7705S-027_This_bottle_of_Jack_Daniels_Old_No._7_whiskey_was_presented_to_retired_Navy_Capt._Ted_Davis_on_the_40th_anniversary_of_the_surfacing_of_a_Soviet_submarine.jpg/500px-thumbnail.jpg",
  },
  {
    id: "P020",
    name: "Maker's Mark",
    category: "Bourbon",
    size: "750ml",
    qty: 15,
    reorderPoint: 12,
    purchasePrice: 25.0,
    sellingPrice: 38.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(17),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Bottle_of_Maker%27s_Mark_Whisky.JPG/500px-Bottle_of_Maker%27s_Mark_Whisky.JPG",
  },
  {
    id: "P021",
    name: "Woodford Reserve",
    category: "Bourbon",
    size: "750ml",
    qty: 10,
    reorderPoint: 10,
    purchasePrice: 33.0,
    sellingPrice: 49.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(21),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/WR_DS.jpg/500px-WR_DS.jpg",
  },
  {
    id: "P022",
    name: "Jameson Irish Whiskey",
    category: "Whiskey",
    size: "750ml",
    qty: 21,
    reorderPoint: 15,
    purchasePrice: 24.0,
    sellingPrice: 37.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(13),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Jameson_Irish_Whiskey_%2811898467796%29.jpg/500px-Jameson_Irish_Whiskey_%2811898467796%29.jpg",
  },
  {
    id: "P023",
    name: "Jim Beam",
    category: "Bourbon",
    size: "1L",
    qty: 16,
    reorderPoint: 15,
    purchasePrice: 17.0,
    sellingPrice: 27.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(6),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Jim_Bean_Kentucky_Straight_Bourbon_%282025-12-19%29.jpg/500px-Jim_Bean_Kentucky_Straight_Bourbon_%282025-12-19%29.jpg",
  },
  {
    id: "P024",
    name: "Johnnie Walker Black Label",
    category: "Scotch",
    size: "750ml",
    qty: 19,
    reorderPoint: 12,
    purchasePrice: 34.0,
    sellingPrice: 52.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(24),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Photography_by_David_Adam_Kess_Johnnie_Walker_Black_Label_Whisky.jpg/500px-Photography_by_David_Adam_Kess_Johnnie_Walker_Black_Label_Whisky.jpg",
  },
  {
    id: "P025",
    name: "Glenlivet 12",
    category: "Scotch",
    size: "750ml",
    qty: 6,
    reorderPoint: 10,
    purchasePrice: 41.0,
    sellingPrice: 62.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(33),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/e/e1/The_Glenlivet_Single_Malt_Scotch_Whisky_15_years_old.jpg",
  },
  {
    id: "P026",
    name: "Macallan 12",
    category: "Scotch",
    size: "750ml",
    qty: 5,
    reorderPoint: 8,
    purchasePrice: 58.0,
    sellingPrice: 89.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(33),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Macallan_whisky%2C_12-15-18_years.jpg/500px-Macallan_whisky%2C_12-15-18_years.jpg",
  },
  {
    id: "P027",
    name: "Absolut",
    category: "Vodka",
    size: "1L",
    qty: 24,
    reorderPoint: 15,
    purchasePrice: 19.0,
    sellingPrice: 29.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(9),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Absolut_Vodka_02.jpg/500px-Absolut_Vodka_02.jpg",
  },
  {
    id: "P028",
    name: "Ketel One",
    category: "Vodka",
    size: "750ml",
    qty: 12,
    reorderPoint: 10,
    purchasePrice: 21.0,
    sellingPrice: 34.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(19),
  },
  {
    id: "P029",
    name: "Bombay Sapphire",
    category: "Gin",
    size: "750ml",
    qty: 17,
    reorderPoint: 10,
    purchasePrice: 23.0,
    sellingPrice: 36.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(11),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Assorted_gin_bottles_on_a_store_shelf.jpg/500px-Assorted_gin_bottles_on_a_store_shelf.jpg",
  },
  {
    id: "P030",
    name: "Tanqueray",
    category: "Gin",
    size: "750ml",
    qty: 9,
    reorderPoint: 10,
    purchasePrice: 22.0,
    sellingPrice: 35.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(27),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/a/af/Tanqueray_bottle_Gin.png",
  },
  {
    id: "P031",
    name: "Hendrick's",
    category: "Gin",
    size: "750ml",
    qty: 13,
    reorderPoint: 8,
    purchasePrice: 31.0,
    sellingPrice: 47.99,
    expiryDate: "",
    vendor: "Republic National Distributing",
    receivedDate: daysAgoIso(16),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Hendricks_Gin_Glorifier_balance_antique.jpg/500px-Hendricks_Gin_Glorifier_balance_antique.jpg",
  },
  {
    id: "P032",
    name: "Bacardi Superior",
    category: "Rum",
    size: "750ml",
    qty: 26,
    reorderPoint: 18,
    purchasePrice: 15.0,
    sellingPrice: 24.99,
    expiryDate: "",
    vendor: "Coastal Beverage Supply",
    receivedDate: daysAgoIso(10),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Bacardi_rum_bottle.jpg/500px-Bacardi_rum_bottle.jpg",
  },
  {
    id: "P033",
    name: "Captain Morgan Spiced",
    category: "Rum",
    size: "750ml",
    qty: 19,
    reorderPoint: 15,
    purchasePrice: 16.5,
    sellingPrice: 26.99,
    expiryDate: "",
    vendor: "Coastal Beverage Supply",
    receivedDate: daysAgoIso(14),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Captain_Morgan_Spiced_Rum_Bottles.jpg/500px-Captain_Morgan_Spiced_Rum_Bottles.jpg",
  },
  {
    id: "P034",
    name: "Malibu Coconut",
    category: "Rum",
    size: "750ml",
    qty: 12,
    reorderPoint: 10,
    purchasePrice: 15.5,
    sellingPrice: 24.99,
    expiryDate: "",
    vendor: "Coastal Beverage Supply",
    receivedDate: daysAgoIso(19),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/SelvaRey_Chocolate%2C_White%2C_and_Coconut_Rums_against_backdrop.jpg/500px-SelvaRey_Chocolate%2C_White%2C_and_Coconut_Rums_against_backdrop.jpg",
  },
  {
    id: "P035",
    name: "Don Julio Blanco",
    category: "Tequila",
    size: "750ml",
    qty: 18,
    reorderPoint: 10,
    purchasePrice: 32.0,
    sellingPrice: 54.99,
    expiryDate: "",
    vendor: "Southern Glazer's Wine & Spirits",
    receivedDate: daysAgoIso(12),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Don_Julio_Blanco_Tequila_01.tif/lossy-page1-500px-Don_Julio_Blanco_Tequila_01.tif.jpg",
  },
  // Espolòn / Cazadores, not Casamigos or 1800 Coconut — those two are
  // deliberately kept OUT of the catalog; SAMPLE_INQUIRIES below tests the
  // "asked about but not carried" demand-signal path against exactly those
  // two names, and adding them as real products would contradict that.
  {
    id: "P036",
    name: "Espolòn Blanco",
    category: "Tequila",
    size: "750ml",
    qty: 14,
    reorderPoint: 10,
    purchasePrice: 21.0,
    sellingPrice: 33.99,
    expiryDate: "",
    vendor: "Southern Glazer's Wine & Spirits",
    receivedDate: daysAgoIso(10),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Espolon_Tequila_Blanco_02.tif/lossy-page1-500px-Espolon_Tequila_Blanco_02.tif.jpg",
  },
  {
    id: "P037",
    name: "Cazadores Reposado",
    category: "Tequila",
    size: "750ml",
    qty: 7,
    reorderPoint: 10,
    purchasePrice: 23.0,
    sellingPrice: 37.99,
    expiryDate: "",
    vendor: "Southern Glazer's Wine & Spirits",
    receivedDate: daysAgoIso(25),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Tequila_Corralejo_100ml_%28Reposado%29%2C_Mexico%2C_2026-03-30.jpg/500px-Tequila_Corralejo_100ml_%28Reposado%29%2C_Mexico%2C_2026-03-30.jpg",
  },
  {
    id: "P038",
    name: "Remy Martin VSOP",
    category: "Cognac",
    size: "750ml",
    qty: 22,
    reorderPoint: 15,
    purchasePrice: 42.0,
    sellingPrice: 74.99,
    expiryDate: "",
    vendor: "Southern Glazer's Wine & Spirits",
    receivedDate: daysAgoIso(18),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/R%C3%A9my_Martin_VSOP.jpg/500px-R%C3%A9my_Martin_VSOP.jpg",
  },
  {
    id: "P039",
    name: "Grand Marnier",
    category: "Liqueur",
    size: "750ml",
    qty: 16,
    reorderPoint: 10,
    purchasePrice: 28.0,
    sellingPrice: 44.99,
    expiryDate: "",
    vendor: "Southern Glazer's Wine & Spirits",
    receivedDate: daysAgoIso(20),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Grand_Marnier_Bottle.jpg/500px-Grand_Marnier_Bottle.jpg",
  },
  {
    id: "P040",
    name: "Kahlua Coffee Liqueur",
    category: "Liqueur",
    size: "750ml",
    qty: 20,
    reorderPoint: 12,
    purchasePrice: 16.0,
    sellingPrice: 26.99,
    expiryDate: "",
    vendor: "Coastal Beverage Supply",
    receivedDate: daysAgoIso(14),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Kahl%C3%BAa_700ml_imported_glass_bottle_-_transparent_%282016%29.png/500px-Kahl%C3%BAa_700ml_imported_glass_bottle_-_transparent_%282016%29.png",
  },
  {
    id: "P041",
    name: "Heineken 6-pack",
    category: "Beer",
    size: "6-pack",
    qty: 14,
    reorderPoint: 20,
    purchasePrice: 8.2,
    sellingPrice: 13.99,
    expiryDate: "2026-08-20",
    vendor: "Coastal Beverage Supply",
    receivedDate: daysAgoIso(4),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Botella_de_cerveza_%28Heineken%29.JPG/500px-Botella_de_cerveza_%28Heineken%29.JPG",
  },
  {
    id: "P042",
    name: "Kendall-Jackson Chardonnay",
    category: "Wine",
    size: "750ml",
    qty: 22,
    reorderPoint: 12,
    purchasePrice: 9.0,
    sellingPrice: 16.99,
    expiryDate: "2027-06-01",
    vendor: "Coastal Beverage Supply",
    receivedDate: daysAgoIso(28),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Vina_Maipo_-_Chardonnay_Valle_Central_2010.JPG/500px-Vina_Maipo_-_Chardonnay_Valle_Central_2010.JPG",
  },
  {
    id: "P043",
    name: "Josh Cellars Cabernet",
    category: "Wine",
    size: "750ml",
    qty: 18,
    reorderPoint: 12,
    purchasePrice: 10.0,
    sellingPrice: 18.99,
    expiryDate: "2027-08-01",
    vendor: "Coastal Beverage Supply",
    receivedDate: daysAgoIso(28),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Glass_of_Red_Wine_with_a_bottle_of_Red_Wine_-_Evan_Swigart.jpg/500px-Glass_of_Red_Wine_with_a_bottle_of_Red_Wine_-_Evan_Swigart.jpg",
  },
  {
    id: "P044",
    name: "Malbec Reserva",
    category: "Wine",
    size: "750ml",
    qty: 11,
    reorderPoint: 12,
    purchasePrice: 11.0,
    sellingPrice: 19.99,
    expiryDate: "2027-05-15",
    vendor: "Coastal Beverage Supply",
    receivedDate: daysAgoIso(28),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Wine_Tasting-_Malbec.jpg/500px-Wine_Tasting-_Malbec.jpg",
  },
  {
    id: "P045",
    name: "Veuve Clicquot Brut",
    category: "Champagne",
    size: "750ml",
    qty: 4,
    reorderPoint: 6,
    purchasePrice: 38.0,
    sellingPrice: 64.99,
    expiryDate: "2028-01-01",
    vendor: "Coastal Beverage Supply",
    receivedDate: daysAgoIso(35),
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Champagne_Veuve_Clicquot_Brut.jpg/500px-Champagne_Veuve_Clicquot_Brut.jpg",
  },
];

export const SAMPLE_SALES: Sale[] = [
  { id: "s1", productId: "P001", qty: 14, date: daysAgoIso(3) },
  { id: "s2", productId: "P004", qty: 1, date: daysAgoIso(6) },
  { id: "s3", productId: "P008", qty: 10, date: daysAgoIso(2) },
  { id: "s4", productId: "P010", qty: 1, date: daysAgoIso(5) },
  { id: "s5", productId: "P015", qty: 1, date: daysAgoIso(9) },
  { id: "s6", productId: "P017", qty: 4, date: daysAgoIso(4) },
  { id: "s7", productId: "P018", qty: 3, date: daysAgoIso(4) },

  // New products' sales. P026 (Macallan 12), P030 (Tanqueray), and P041
  // (Heineken 6-pack) are deliberately left with zero sales, mirroring the
  // Baileys "zero recent sales" High-risk pattern above — but only for
  // those three, so it's not a blanket rule across the whole catalog.
  { id: "s8", productId: "P019", qty: 3, date: daysAgoIso(2) },
  { id: "s9", productId: "P020", qty: 2, date: daysAgoIso(4) },
  { id: "s10", productId: "P021", qty: 1, date: daysAgoIso(6) },
  { id: "s11", productId: "P022", qty: 4, date: daysAgoIso(1) },
  { id: "s12", productId: "P023", qty: 2, date: daysAgoIso(3) },
  { id: "s13", productId: "P024", qty: 2, date: daysAgoIso(5) },
  { id: "s14", productId: "P025", qty: 1, date: daysAgoIso(8) },
  { id: "s15", productId: "P027", qty: 3, date: daysAgoIso(2) },
  { id: "s16", productId: "P028", qty: 1, date: daysAgoIso(7) },
  { id: "s17", productId: "P029", qty: 2, date: daysAgoIso(3) },
  { id: "s18", productId: "P031", qty: 1, date: daysAgoIso(6) },
  { id: "s19", productId: "P032", qty: 5, date: daysAgoIso(1) },
  { id: "s20", productId: "P033", qty: 3, date: daysAgoIso(2) },
  { id: "s21", productId: "P034", qty: 2, date: daysAgoIso(4) },
  { id: "s22", productId: "P035", qty: 2, date: daysAgoIso(3) },
  { id: "s23", productId: "P036", qty: 1, date: daysAgoIso(5) },
  { id: "s24", productId: "P037", qty: 1, date: daysAgoIso(9) },
  { id: "s25", productId: "P038", qty: 1, date: daysAgoIso(7) },
  { id: "s26", productId: "P039", qty: 1, date: daysAgoIso(6) },
  { id: "s27", productId: "P040", qty: 2, date: daysAgoIso(3) },
  { id: "s28", productId: "P042", qty: 2, date: daysAgoIso(4) },
  { id: "s29", productId: "P043", qty: 1, date: daysAgoIso(5) },
  { id: "s30", productId: "P044", qty: 1, date: daysAgoIso(8) },
  { id: "s31", productId: "P045", qty: 1, date: daysAgoIso(10) },
];

export const SAMPLE_INQUIRIES: Inquiry[] = [
  {
    id: "i1",
    product: "Casamigos Reposado",
    date: daysAgoIso(11),
    carried: false,
  },
  {
    id: "i2",
    product: "Casamigos Reposado",
    date: daysAgoIso(9),
    carried: false,
  },
  {
    id: "i3",
    product: "Casamigos Reposado",
    date: daysAgoIso(7),
    carried: false,
  },
  {
    id: "i4",
    product: "1800 Coconut Tequila",
    date: daysAgoIso(6),
    carried: false,
  },
  {
    id: "i5",
    product: "1800 Coconut Tequila",
    date: daysAgoIso(5),
    carried: false,
  },
];
